### ISSUE TITLE
more information about "vectors"? 

### ISSUE THREAD

**Issue by Shicheng-Guo** [StevenWingett/FastQ-Screen#13]
Dear Steven, 

Can I have more information about the category of "vectors" in the fastq_screen? 

Thanks. 

Shicheng

**Comment by StevenWingett** [comment]
Hi Shicheng,

Thanks for your message.  We have placed more information on our genomes in the FastQ Screen configuration file.  The vectors were taken from:

http://www.ncbi.nlm.nih.gov/VecScreen/UniVec.html

All the best,

Steven
