### ISSUE TITLE
How to extract rRNA reads from metagenomic RNA-seq data

### ISSUE THREAD

**Issue by Shicheng-Guo** [StevenWingett/FastQ-Screen#14]
Hi Steven, 

I notice fastq_screen could counts the proportion of rRNA in the metagenome fastq files. I want to know how to extract all the rRNA reads. I want to do some further analysis to rRNA reads from RNA-seq data of metagenome samples. 

Thanks.

**Comment by StevenWingett** [comment]
Hi Shicheng,

FastQ Screen may be used for filtering datasets and extracting reads mapping to pre-specified genomes.  For further details see:

https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/_build/html/index.html#filtering-fastq-files

There is probably no one way to do this, and different strategies may have different advantages and disadvantages.  If I were you, I would identify the likely species and genera you intend to sequence.  I would then download the relevant genomes from online repositories and extract genome regions corresponding to rRNA genes.  You could then make a virtual genome of these sequences and index with Bowtie2/BWA.  Then run FastQ Screen on your experimental FASTQ files, filtering for reads mapping to your virtual genome.

That is a rough guide and you will need to read a more around the subject and decide on the questions you need to answer in your research.  Anyway, I hope that helps.

All the best,
Steven
