### ISSUE TITLE
[Feature Request] Simplify adding genomes to config file

### ISSUE THREAD

**Issue by FelixKrueger** [StevenWingett/FastQ-Screen#2]
It would be nice to add a new option to FastQ Screen to streamline adding new genomes. One might e.g.
specify:

 `--new_genome_name Potato` and `--new_genome_path /bi/scratch/Genomes/Solanum_tuberosum`
or
 `--new_genome_name Mycoplasma` and `--new_genome_path /bi/scratch/Genomes/Mycoplasma`

FastQ Screen would then scan the specified folder for valid Bowtie2/BWA/Bismark indexes, and modify the Config file accordingly. Many thanks!

**Comment by StevenWingett** [comment]
Feature --add_genome created.
