### ISSUE TITLE
FastQ Screen Anaconda

### ISSUE THREAD

**Issue by StevenWingett** [StevenWingett/FastQ-Screen#22]
Make FastQ Screen available on via Anaconda.

**Comment by druvus** [comment]
FastQ-Screen is available through Bioconda: https://anaconda.org/bioconda/fastq-screen

**Comment by StevenWingett** [comment]
I have updated the documentation to reference this Bioconda package (commit: e27e353).  I tested the install via Bioconda on an Ubuntu Bionic Beaver Minimal Install OS and it appeared to work, although admittedly I did not try map reads.
