### ISSUE TITLE
pair-end screen

### ISSUE THREAD

**Issue by jeongmeani** [StevenWingett/FastQ-Screen#26]
Hi,

using fastq-screen, i check contamination of ngs data.
but i got pair-end data and fastq-screen does not support this mode.

so how can i handle this?
would i merge R1 and R2 to check the sample itself?

Best Regards

Jeongmin

**Comment by StevenWingett** [comment]
Hi Jeongmin,

Process the R1 and R2 files separately with FastQ Screen.  

You are trying to identify contamination and mapping the files separately is a better way to do this.  For example, suppose the contamination was more prevalent in, say R1.  By mapping separately you would be able to identify this bias.

I hope that helps.

All the best,

Steven
