### ISSUE TITLE
SAM or BAM files extraction after alignment

### ISSUE THREAD

**Issue by Shivangiver** [StevenWingett/FastQ-Screen#27]
Is there anyway to  extract SAM or BAM files from the alignment process?

**Comment by StevenWingett** [comment]
Hi,

FastQ Screen allows you to generate FASTQ files in which the headers of each read list the genomes to which that read mapped.  This is the --tag command.  You can also filter these tagged FASTQ files to extract reads that mapped to specified genomes (--filter).  

For more information, got to:
https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/_build/html/index.html#filtering-fastq-files

If you need BAM/SAM files, simply process a FASTQ file with Bowtie/Bowtie2/BWA.

I hope that helps.

Steven
