### ISSUE TITLE
[Enhancement] Add option to download bisulfite indexes 

### ISSUE THREAD

**Issue by FelixKrueger** [StevenWingett/FastQ-Screen#3]
If possible, could you please add another option `--bisulfite` which, when specified in conjunction with `--get_genomes`, downloads pre-made indexes for Bismark in addition to the Bowtie2 indexes you are already offering.

It might be useful to add to the `--help` text that this will be in the range of 10-15GB for each normal as well as bisulfite indexes.

Many thanks! Felix
![redhathero](https://user-images.githubusercontent.com/5870509/51915617-789ae700-23d3-11e9-9c19-7270b2218b4e.jpg)

**Comment by DiegoZavallo** [comment]
Hi, I was wondering is this enhancement was added. I also want to mapped my reads in --bisulfite mode.
Could I just copy the bisulfite index folder into the /Genomes path?

**Comment by StevenWingett** [comment]
Hi,

This feature will be included in the next update, which should be released in the next day or so.  You can of course still use bisulfite genomes that you already have by making sure they are referred to in the configuration file.

All the best,

Steven

**Comment by DiegoZavallo** [comment]
Thanks Steve, looking forward to the next update.
By referred to my bisulfite genomes, do you mean that I have to referred to /path/to/Bisulifte_Genome/ where inside that folder CT_conversion and GA_conversion folders are?

Best

Diego

**Comment by StevenWingett** [comment]
Hi,

Create a folder called "Bisulfite_Genome" inside the folder that contains the standard Bowtie2 genome index files. 

Then copy the relevant "CT_conversion" and "GA_conversion" Bismark folders to the Bisulfite_Genome folder.

Hope that helps,

Steven

**Comment by StevenWingett** [comment]
This is done and will be included in the next upcoming release.
