### ISSUE TITLE
How to run Fastq-screen on paired end RNA-Seq data? 

### ISSUE THREAD

**Issue by lida-R** [StevenWingett/FastQ-Screen#32]
Hello There,

I noticed that the flag for paired end data is removed in one of the version. Could you let me know how I can run Fastq-Screen for paired data? Should I run each read separately? 

Thank you,
Lida

**Comment by StevenWingett** [comment]
Hi Lida,

Thanks for your message.  Yes, process each file separately even for paired-end data.  For Quality Control purposes it is not necessary to map in paired-end mode - indeed it is often beneficial not to do so, for a contaminant may be present in one read but not its pair.  (If you are filtering the data however with FastQ Screen, you may need to pair the filtered reads after processing.)

All the best,
Steven

**Comment by lida-R** [comment]
Thank you for your explanation.
So you meant I need to add up the number of reads hit genome in read1 and
read2?
For example

[image: image.png]
Thank you for your help,
Lida

**Comment by StevenWingett** [comment]
Hi Lida,

It's not necessarily that simple.  For example in a read pair, readF might map to genome x, but then readR does not.  For QC purposes you should be able to see what is going on by mapping in single-end mode using FastQ Screen.

You can of course filter in single end mode, but it is important that you process the resulting FASTQ files so the corresponding pairs are on corresponding lines in the file.  Also, if a readF maps to genome x, but readR does not then then the readF will still need to be removed from the final file.

I hope that helps.

All the best,

Steven

**Comment by ahdee** [comment]
Hi Linda, piggy backing of this OP's question. What if one of the read pair had more contimation then another, say mouse ,and was filtered out.  In that case each of the fastq R1 and R2 are not unmatched.  In this case, would there be any issues if I were to say aligned to STAR and count the reads?

**Comment by StevenWingett** [comment]
Hi,

Thanks for your message.  I'd like to refer you to this conversation about pairing FASTQ reads after FastQ-Screen filtering:
https://github.com/StevenWingett/FastQ-Screen/issues/31

I hope this helps.

Thanks,
Steven
