### ISSUE TITLE
How many nucleotides  (bp) need to be matched between one read of our genome and reference genome?

### ISSUE THREAD

**Issue by lida-R** [StevenWingett/FastQ-Screen#35]
Hello, I searched in your paper and manual but couldn't find how many nucleotides  (bp) need to be matched between one read of our genome and reference genome?

Thank you for your help.
Lida

**Comment by StevenWingett** [comment]
Hi Lida,

Thank you for your email. I am not sure I completely understand the question.  Do you mean between the reference genome and a sequenced read?  

If so, remember it is actually Bowtie/Bowtie2 or BWA that does the aligning.  If you refer to the relevant software manual you will see the degree of overlap needed for a successful alignment.  The exact mapping parameters passed to these aligners from FastQ Screen will be in the source code.  Please let me know if you need help finding these commands.

Does that help?

All the best,
Steven

**Comment by StevenWingett** [comment]
I presume the query was resolved.
