### ISSUE TITLE
Changeable Bowtie2 options (--very-fast)

### ISSUE THREAD

**Issue by LucasFVoges** [StevenWingett/FastQ-Screen#37]
I used fastQScreen and had many unmapped reads (Hit_No_Genomes). 

I wondered if the options for Bowtie2 "--very-sensitive-local" would result in a better mapping. Indeed  around 20 % of the unmapped reads are now sorted. 

I changed the line (1259) inside the fastq_screen file for this. I think it is not possible to change this via the command line options for the aligner.

Is there any reason why this is not changeable via the options? Do i miss something important here? In the manual it is stated not to change this:

> bowtie2 <text> : Specify extra parameters to be passed to Bowtie 2. These parameters should be quoted to clearly delimit Bowtie 2 parameters from FastQ Screen parameters. You should not try to use this option to override the normal search or reporting options for bowtie which are set automatically but it might be useful to allow reads to be trimmed before alignment etc.

**Comment by StevenWingett** [comment]
Hi,

Thanks for your message.

FastQ Screen was originally designed as a QC tool to allow users to quickly ascertain the quality of their sequenced libraries, therefore mapping speed was a priority.  Generally, researchers need to know whether contamination is present at all and would like a rough measure of the degree of such contamination

However, I can potentially see the value of mapping with greater sensitivity when filtering FASTQ files.  Perhaps FastQ Screen could run with more sensitive mapping parameters when the --filter (or --tag) option has been specified.   Are you able to send over your summary results when mapping with the 2 different settings?

Regarding the options.  I want FastQ Screen to be easy-to-use.  Consequently, I don’t want the end-user to have to worry about Bowtie/Bowtie2/BWA options.  For certain applications (e.g. if reads need to be trimmed at the ends, allowing extra options to be passed to the aligner is simple and useful). 

Many thanks,

Steven

**Comment by LucasFVoges** [comment]
Hi Steven,

thanks for your reply. I just tried to use this on the test dataset. You can clearly see a difference in the two results (data attached).

Best wishes, Lucas

[fqs_test_bowtie2.zip](https://github.com/StevenWingett/FastQ-Screen/files/6932163/fqs_test_bowtie2.zip)

**Comment by StevenWingett** [comment]
Hi,

Thanks for sending me those summary reports.   My first thought is actually that the mapping efficiency is high with both mapping strategies.   97.7% mapped with the current fast mapping parameters is still very high.  So, that looks as though it has working as it is supposed to do.

I think there is always a trade-off between what should be considered mapped/not mapped.  While better mapping to the target genome is good, finding more obscure matches to other genomes may not be desirable in some instances (notice how the proportion of reads mapping to rat increases with the more sensitive mapping).

I hope that you are finding FastQ Screen useful in your research.

All the best,
Steven
