### ISSUE TITLE
R1 and R2 generate map differently to the human genome 

### ISSUE THREAD

**Issue by simonovae** [StevenWingett/FastQ-Screen#38]
I run FastQScreen on my WGS samples and I got different values for mapping read1 and read 2 to the genome? I can't understand what causes this 2 % bias for reverse read? The example is given below.

| Name | Human counts | Human % | total_reads | HOMD counts | HOMD % | No hits counts | No hits % |
|:----:|:------------:|:-------:|:-----------:|:-----------:|:------:|:--------------:|:---------:|
| A_R1 |        99308 |   99.32 |       99996 |        3248 |   3.26 |            679 |      0.68 |
| A_R2 |        97035 |   97.03 |       99996 |        4240 |   4.24 |           2869 |      2.87 |
| B_R1 |        99538 |   99.55 |       99994 |        4313 |   4.33 |            439 |      0.44 |
| B_R2 |        97512 |   97.52 |       99994 |        5330 |   5.34 |           2369 |      2.37 |
| C_R1 |        99432 |   99.42 |      100004 |        3161 |   3.15 |            570 |      0.57 |
| C_R2 |        97515 |   97.51 |      100004 |        4366 |   4.37 |           2410 |      2.41 |
| D_R1 |        99557 |   99.55 |      100004 |        4329 |   4.32 |            420 |      0.42 |
| D_R2 |        97522 |   97.52 |      100004 |        5596 |   5.59 |           2310 |      2.31 |

**Comment by StevenWingett** [comment]
Hi,

Thanks for your message.

I'm not actually too surprised by this.  While working on paired-end data I've seen may instances of Read1 vs Read2 biases.  

Have you generated a FastQC report ( https://www.bioinformatics.babraham.ac.uk/projects/fastqc/ )?  If you look at this, do you see any obvious R1/R biases in the data (e.g. base calling quality differences)?

Does that help?

All the best,

Steven

**Comment by simonovae** [comment]
Hi,

thanks for the response I have not noticed any difference in base qualities in my samples between R1 and R2. I attached fastqc report below.

Regards,

Ekaterina
[multiqc_report_wes.zip](https://github.com/StevenWingett/FastQ-Screen/files/7029792/multiqc_report_wes.zip)

**Comment by StevenWingett** [comment]
Hi Ekaterina,

The profiles are very similar, but they are not identical, and the mapping efficiencies only differ by a couple of percent.  It is not unusual to see slight biases between R1 and R2 and I would not be concerned about this with regard to your experiment.

If you are interested in pursuing this further however, you could use the FastQ Screen --filter option to extract reads that map/do not map to different genomes.

All the best,

Steven

**Comment by simonovae** [comment]
Thanks for the response.
