### ISSUE TITLE
Error while performing --bisulfite read mapping

### ISSUE THREAD

**Issue by rbpisupati** [StevenWingett/FastQ-Screen#46]
Hello !

I am running fastq-screen installed through conda. But I am getting this error 

```
> cat .command.err
Using fastq_screen v0.14.0
Defaulting to Bowtie 2 for --bisulfite mode
Reading configuration from 'FastQ_Screen_Genomes/fastq_screen.conf'
Adding database Rat
Adding database Drosophila
Adding database Worm
Adding database Yeast
Adding database Arabidopsis
Adding database Ecoli
Adding database PhiX
Adding database Lambda
Adding database Vectors
Adding database Adapters
Using 8 threads for searches
Option --subset set to 500000 reads
Processing test_reads_1.fq
Counting sequences in test_reads_1.fq
Not making subset of 500000 since 6146 actual sequences is too low or close enough
Searching test_reads_1.fq_temp_subset.fastq against Rat
Could not run Bismark with command: '/users/rahul.pisupati/.conda/envs/fastq_screen/bin/bismark  --path_to_bowtie /users/rahul.pisupati/.conda/envs/fastq_screen/bin/ --ambiguous --bowtie2   --non_directional --prefix Rat --output_dir work_nf/bf/158e263020dddd370b9b9d6fbc42c9/ FastQ_Screen_Genomes/Rat/ work_nf/bf/158e263020dddd370b9b9d6fbc42c9/test_reads_1.fq_temp_subset.fastq 1>/dev/null 2>work_nf/bf/158e263020dddd370b9b9d6fbc42c9/aligner_standard_error.qd9tUFOW.txt'.
```

But I could run the exact command directly on the terminal. Can you please check if there is something I am missing?

fastq-screen works perfectly well and generates png output without `--bisulfite` option.

Cheers, 
R

**Comment by StevenWingett** [comment]
Hi,

Thanks for your email.  That fact that you can run the command directly but not through Conda makes me suspect that this is something to do with the Conda setup.

I don't produce the Conda setup myself, so I suggest contacting the person who wrote it.  Out of interest, what is the link to this Conda build?

As an alternative, I suggest that you simply try download the FastQ Screen and Bismark scripts.  They are simple Perl scripts with only a few dependancies (such as the Bowtie2 aligner).  It should (hopefully) be nearly as simple to install this way as via Conda.  If you do decide to do this, but encounter problems, then please let me know and I'll try an help.

All the best,
Steven

**Comment by StevenWingett** [comment]
I'm not sure if the filer of the issue contacted the Conda team, so I shall close this issue.

**Comment by rbpisupati** [comment]
Hey!

No, I havent contacted conda team! I got into working on some other project! I will get back to this, will try FastQ screen as you suggested. 

Cheers, 
R

**Comment by StevenWingett** [comment]
Hi,

No worries.  I was just closing older Git jobs that seemed not to be progressing.

Many thanks,
Steven
