### ISSUE TITLE
Wrong path in config file when using --get_genomes

### ISSUE THREAD

**Issue by tdido** [StevenWingett/FastQ-Screen#5]
The config file obtained with --get_genomes has a path which I assume is from a Babraham Institute server. I guess this is due to the replacement code failing in the following line, probably due to the path being present in the original config file [1] instead of the placeholder text.

https://github.com/StevenWingett/FastQ-Screen/blob/16c4cb45e725d46dc07c43e90fa448d79cdaa94b/fastq_screen#L2407
[1] http://ftp1.babraham.ac.uk/ftpusr24/FastQ_Screen_Genomes/fastq_screen.conf

**Comment by StevenWingett** [comment]
Hi,

Sorry, I've just seen your GitHub message.  I'm not sure what problem you are having.  What happens if you type the following?

fastq_screen --get_genomes

I know this feature was not working yesterday.  But it should have been working when you posted your message, and it should be working now.

Please let me know how you get on.

Best regards,

Steven

**Comment by tdido** [comment]
Hi Steven.

The index files are downloaded correctly, the problem is with the configuration file you get: the "fastq_screen.conf" you end up with is a verbatim copy of the one I linked above, hence containing paths starting with "/bi/scratch/wingetts/FASTQ_Screen_Paper/...".

It looks like the line of code I linked above is looking for a "[FastQ_Screen_Genomes_Path]" placeholder to replace it with the output directory, hence customising the config file automatically and leaving it ready to be used in the local system. Is that not the case?

**Comment by StevenWingett** [comment]
Hi,

I see what you mean.  I'm working on an update.

All the best,

Steven

**Comment by StevenWingett** [comment]
Hi,

Please let me know if it now works (you don't need to update FastQ Screen).

Regards,

Steven

**Comment by tdido** [comment]
Yep, the new config file works. Thanks!
