### ISSUE TITLE
Support for STAR

### ISSUE THREAD

**Issue by perinom** [StevenWingett/FastQ-Screen#52]
Amazing tool, thanks!

I was wondering if there's any plan to include fast splice-aware mappers like STAR to the list of supported tools

Thanks!

**Comment by StevenWingett** [comment]
Hi,

Thanks for your kind comments.

At the moment I am not planning to add STAR (or indeed HISAT2) as an aligner for FastQ Screen.  The tool is primarily a QC application, which should almost always give the necessary QC details without the need for splice-aware alignment.  Is this setup causing particular problems?

I hope that answers your query.

Steven
PS I do hope to add the minimap aligner in the not-too-distant future for the mapping of very long reads.

**Comment by perinom** [comment]
Thanks for your reply

I was asking mostly because I use project-dedicated environments, if the project only contains transcriptomics data it would be good to avoid adding additional tools and 
the relative genome indices. 

Spliced reads might also not map, but I agree the amount of reads probably won't dramatically change the results for QC assessment
