### ISSUE TITLE
Only "no hits" in the output!!

### ISSUE THREAD

**Issue by Hela06** [StevenWingett/FastQ-Screen#56]
Hi!

I used FastQ-Screen in order to test smallRNA sequencing data. As you can see in the attached report,  my human samples does not map  in any reference genome.  Can you explain me what could be the problem in my samples?

Thank you so much,
Hela
[FastQScreen_report.pdf](https://github.com/StevenWingett/FastQ-Screen/files/9423847/FastQScreen_report.pdf)

**Comment by StevenWingett** [comment]
Hi,

Well there does seem to be human DNA, but not very much.  It looks as though something has gone wrong somewhere.   My thoughts are:

1) Presumably you have made a FastQC report?  Does it look okay?

2) Are there sequences before the target human DNA (e.g. in-sequence barcodes) that are preventing mapping?

3)  Does mapping independently to the human reference genome using another program also give poor results?

Regards,
Steven

**Comment by Hela06** [comment]
Thank you for the prompt reply!

1.Yes, I did. The FastQC is not so good, but since the thresholds used to assign the flags are less reliable with small RNA-Seq, a module result that has a “Warn” or “Fail” flag does not necessarily mean that the sequence run failed.
2. I removed them along with the adapters.
3. I aligned using both bowtie and Salmon, and the alignment rate is less than 1%. So, it confirms the fastQ-Screen result. 

Since the company confirmed that the library preparation was good, what could be the issue? 

Thank you, 
Hela

**Comment by StevenWingett** [comment]
Hi,

This seems to be some kind of experimental problem.  Are you able to discuss this with the company?

Also, are there any repeated sequences in the FastQC report that may explain the problem?  Have you tried using tools such as Kraken to identify the origin of your reads?

Regards, 
Steven
