### ISSUE TITLE
Question- how to include no hit reads into final fastq data while screening?

### ISSUE THREAD

**Issue by anilchauhanhp9** [StevenWingett/FastQ-Screen#57]
Hi, i ran fastqc-screen on bacterial fastq data. As the reference data contain only E. coli data my most of the reads were not mapped to any of the reference genome and comes as no hit. I want to screen my data and take the not hit reads in my final fastq files. How can i do it please suggest.

**Comment by StevenWingett** [comment]
Hi,

Do you know the bacterial species you wish to screen against?  If so, download the reference genome FASTA files for those species and then build Bowtie2 or BWA index files.  You should then be able to map FASTQ reads to your desired reference genomes.

Use the --nohits parameter to extract FASTQ reads that don't map to any of your reference genomes.  (This is described in more detail in the "Filtering FASTQ Files" section of the software documentation found at: https://stevenwingett.github.io/FastQ-Screen/ ).

I hope that helps.

Steven
