### ISSUE TITLE
issue installing..

### ISSUE THREAD

**Issue by chorong5155** [StevenWingett/FastQ-Screen#62]
used this 

 perl -MCPAN -e "install GD"

and got this 
test Summary Report
-------------------
t/windows_bmp.t         (Wstat: 65280 Tests: 1 Failed: 0)
  Non-zero exit status: 255
  Parse errors: Bad plan.  You planned 4 tests but ran 1.
Files=11, Tests=50,  1 wallclock secs ( 0.06 usr  0.02 sys +  0.53 cusr  0.26 csys =  0.87 CPU)
Result: FAIL
Failed 1/11 test programs. 0/50 subtests failed.
make: *** [test_dynamic] Error 255
  RURBAN/GD-2.78.tar.gz
  /usr/bin/make test -- NOT OK
//hint// to see the cpan-testers results for installing this module, try:
  reports RURBAN/GD-2.78.tar.gz
Running make install
  make test had returned bad status, won't install without force

... I don't know how to fix the issue or what the issue is....

any suggestion??

Thanks a lot

**Comment by StevenWingett** [comment]
Hi,

It seems as though you are unable to install the Perl module GD graph on your system.  I would check the GD graph / Perl documentation for more advice on this - I believe the relevant page is here https://metacpan.org/pod/GD::Graph

However, the good news is that this module is NOT essential for FastQ Screen to run - the pipeline will still produce text and HTML summary reports. So, you can still use FastQ Screen, even if this module is not installed.

I hope that helps,
Steven
