### ISSUE TITLE
Unable to download v0.15.3 FastQ-Screen or --get_genomes

### ISSUE THREAD

**Issue by Weng-yann** [StevenWingett/FastQ-Screen#64]
Hi,

I am very new to this and trying to follow the instructions in the introductory videos.

After putting in this command,
"wget https://www.bioinformatics.babraham.ac.uk/projects/fastq_screen/fastq_screen_v0.15.3.tar.gz"

I got this error,
"Resolving www.bioinformatics.babraham.ac.uk (www.bioinformatics.babraham.ac.uk)...149.155.133.4
Connecting to www.bioinformatics.babraham.ac.uk (www.bioinformatics.babraham.ac.uk) | 149.155.133.4 | :443...connected.
HTTP request sent, awaiting response...404 Not Found
2023-08-11 11:10:49 ERROR 404: Not Found."

I can only manage to download v0.14.0 for now. Then, when I used the command "fastq_screen --get_genomes"

The following error appeared, 
"Unknown option: get_genomes
Could not parse options, please adjust configuration."

Could you kindly help me?
Thanks!

**Comment by StevenWingett** [comment]
Hi,

After the videos were made, the FastQ Screen code download archives were moved to GitHub.

Please try the command:

wget https://github.com/StevenWingett/FastQ-Screen/archive/refs/tags/v0.15.3.tar.gz

The --get_genomes option should now work with this version of FastQ Screen.

The FastQ Screen download page is here:
https://github.com/StevenWingett/FastQ-Screen/releases/tag/v0.15.3

The current documentation is here:
https://stevenwingett.github.io/FastQ-Screen/

I hope that helps.

Steven
