### ISSUE TITLE
No reference genomes were configured, please adjust configuration

### ISSUE THREAD

**Issue by Linnaeus001** [StevenWingett/FastQ-Screen#70]
Hi there, I got a problem about fastq-screen and wish to have your help :)
let me show you my process (my aim is to map my data onto some specific species)

Since i build up a new empty  /.conf file for the configuration:
$ touch 1.conf
I edit the content inside of it with emacs (through xmanager7) and got:

$ less 1.conf
BWA /home/DataDisk/th_data/software/envs/bwa
THREADS 8
DATABASE x.ph /home/DataDisk/th_data/workplace/de-contamination/database_custom/x.phaseoli
DATABASE s.mp /home/Datadisk/th_data/workplace/de-contamination/database_custom/s.marcescens_plas
DATABASE s.mc /home/Datadisk/th_data/workplace/de-contamination/database_custom/s.marcescens_chr
DATABASE p.to /home/Datadisk/th_data/workplace/de-contamination/database_custom/p.tolaasii
DATABASE homo /home/Datadisk/th_data/workplace/de-contamination/database_custom/hg19
DATABASE s.gr /home/Datadisk/th_data/workplace/de-contamination/database_custom/GCF_023897955.1_iqSchGreg1.2_genomic
DATABASE e.coli /home/Datadisk/th_data/workplace/de-contamination/database_custom/e.coli

And make index of it:
$ bwa index [each .fa files]
$ ls
1.conf                                       hg19.fa                     s.marcescens_chr.fasta.pac
1.conf~                                      hg19.fa.amb                 s.marcescens_chr.fasta.sa
89-1112_1.fq.gz                              hg19.fa.ann                 s.marcescens_plas.fasta
89-1112_2.fq.gz                              hg19.fa.bwt                 s.marcescens_plas.fasta.amb
e.coli.fasta                                 hg19.fa.pac                 s.marcescens_plas.fasta.ann
e.coli.fasta.amb                             hg19.fa.sa                  s.marcescens_plas.fasta.bwt
e.coli.fasta.ann                             p.tolaasii.fasta            s.marcescens_plas.fasta.pac
e.coli.fasta.bwt                             p.tolaasii.fasta.amb        s.marcescens_plas.fasta.sa
e.coli.fasta.pac                             p.tolaasii.fasta.ann        x.phaseoli.fasta
e.coli.fasta.sa                              p.tolaasii.fasta.bwt        x.phaseoli.fasta.amb
GCF_023897955.1_iqSchGreg1.2_genomic.fa      p.tolaasii.fasta.pac        x.phaseoli.fasta.ann
GCF_023897955.1_iqSchGreg1.2_genomic.fa.amb  p.tolaasii.fasta.sa         x.phaseoli.fasta.bwt
GCF_023897955.1_iqSchGreg1.2_genomic.fa.ann  s.marcescens_chr.fasta      x.phaseoli.fasta.pac
GCF_023897955.1_iqSchGreg1.2_genomic.fa.bwt  s.marcescens_chr.fasta.amb  x.phaseoli.fasta.sa
GCF_023897955.1_iqSchGreg1.2_genomic.fa.pac  s.marcescens_chr.fasta.ann
GCF_023897955.1_iqSchGreg1.2_genomic.fa.sa   s.marcescens_chr.fasta.bwt

However, once I tried to run the command, i got this error:
$ fastq_screen --aligner bwa --conf 1.conf --threads 8 89-1112_1.fq.gz 89-1112_2.fq.gz
Using fastq_screen v0.15.3
Reading configuration from '1.conf'
Using '/home/DataDisk/th_data/software/envs/bwa' as BWA path
Skipping DATABASE 'x.ph' since no BWA index was found at '/home/DataDisk/th_data/workplace/de-contamination/database_custom/x.phaseoli'
Skipping DATABASE 's.mp' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/s.marcescens_plas'
Skipping DATABASE 's.mc' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/s.marcescens_chr'
Skipping DATABASE 'p.to' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/p.tolaasii'
Skipping DATABASE 'homo' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/hg19'
Skipping DATABASE 's.gr' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/GCF_023897955.1_iqSchGreg1.2_genomic'
Skipping DATABASE 'e.coli' since no BWA index was found at '/home/Datadisk/th_data/workplace/de-contamination/database_custom/e.coli'
Using 8 threads for searches
No reference genomes were configured, please adjust configuration.

I really wish to know what happen and thanks so much for your help :)

**Comment by Linnaeus001** [comment]
maybe i should put them into different files?

**Comment by Linnaeus001** [comment]
okay... i got the same problem as issue 61 did. Now it's done

**Comment by StevenWingett** [comment]
Hi,

Is this working now?

Regards,
Steven

**Comment by Linnaeus001** [comment]
> Hi,
> 
> Is this working now?
> 
> Regards, Steven

yeah it work now, the DATABASE work path isn't complete, i forgot to add .fa at the end of the path
