### ISSUE TITLE
Aligner warning: Killed Aligner warning: (ERR): bowtie2-align exited with value 137

### ISSUE THREAD

**Issue by Ayush09-cmd** [StevenWingett/FastQ-Screen#72]
hello,
i am screening the minion generated sequences  of bacterial genome and getting these results. even after geeting killed the sequences are showing hits on these genomes. is it running properly?
![Uploading Screenshot from 2024-09-12 10-09-26.png…]()
[](url)
/fastq_screen combined.fastq --conf /media/ham/General/AYUSH/whole_genome_analysis/fastqscreen/FastQ-Screen-0.15.3/FastQ_Screen_Genomes/fastq_screen.conf --aligner bowtie2 --subset 50000
Using fastq_screen v0.15.3
Reading configuration from '/media/ham/General/AYUSH/whole_genome_analysis/fastqscreen/FastQ-Screen-0.15.3/FastQ_Screen_Genomes/fastq_screen.conf'
Using '/home/ham/miniconda3/envs/fastq-screen/bin/bowtie2' as Bowtie 2 path
Skipping DATABASE 'Bacillushaynessi' since no Bowtie 2 index was found at '/media/ham/General/AYUSH/whole_genome_analysis/fastqscreen/FastQ-Screen-0.15.3/FastQ_Screen_Genomes/bacillus_haynessi'
Adding database Human
Adding database Mouse
Adding database Rat
Adding database Drosophila
Adding database Worm
Adding database Yeast
Adding database Arabidopsis
Adding database Ecoli
Adding database rRNA
Adding database MT
Adding database PhiX
Adding database Lambda
Adding database Vectors
Adding database Adapters
Using 4 threads for searches
Option --subset set to 50000 reads
Processing combined.fastq
Counting sequences in combined.fastq
Making reduced sequence file with ratio 2:1
Searching combined.fastq_temp_subset.fastq against Human
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Mouse
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Rat

Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Drosophila
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Worm
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Yeast
Searching combined.fastq_temp_subset.fastq against Arabidopsis
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against Ecoli
Aligner warning: Killed
Aligner warning: (ERR): bowtie2-align exited with value 137
Searching combined.fastq_temp_subset.fastq against rRNA
Searching combined.fastq_temp_subset.fastq against MT
Searching combined.fastq_temp_subset.fastq against PhiX
Searching combined.fastq_temp_subset.fastq against Lambda
Searching combined.fastq_temp_subset.fastq against Vectors
Searching combined.fastq_temp_subset.fastq against Adapters
Perl module GD::Graph::bars not installed, skipping charts
Processing complete

**Comment by StevenWingett** [comment]
Hi,

Thanks for your message.  I believe Bowtie2 error code 137 means you don't have enough RAM.  Could you allocate more RAM (e.g. 50GB)?

Also, how long are your read?  Bowtie2 is a short read aligner - although I am looking into adding long-read capability next week.

Many thanks,

Steven

**Comment by Ayush09-cmd** [comment]
Actually I had fastq sequences from minion which are long reads would it be an issue

**Comment by StevenWingett** [comment]
Hi again,

Coincidentally, I've just updated FastQ Screen to support long-reads (via using minimap2).
Best,
Steven
