### ISSUE TITLE
Error when running on cluster "undefined symbol: perl_xs_handshake"

### ISSUE THREAD

**Issue by rhondene** [StevenWingett/FastQ-Screen#8]
Hi,
Whenever I try to run fastq_screen on linux-based cluster I get the error "undefined symbol: perl_xs_handshake" I am using Perl 5.24

thanks

**Comment by StevenWingett** [comment]
Hi,
I'm not completely sure what is the problem.  I suspect it is related to where Perl is kept on your system.  Could you change the first line of FastQ Screen to where the version you are using Perl is kept i.e.
#!/[where Perl is stored on your system]

Does that solve the problem?

Regards,

Steven

**Comment by StevenWingett** [comment]
I could not determine the origin of the problem from the reported issue.
