### ISSUE TITLE
[Help/Improvment] - Filter options plus no-hits

### ISSUE THREAD

**Issue by edsonmachado** [StevenWingett/FastQ-Screen#9]
Hi,

I would like to know if it's possible to filter, at the same time, reads that do not map + another filter options?

I mean, some way to avoid multiple filtering rounds in the hypothetical situation described below:

genomes: Human:Mouse:Ecoli:PhiX:Adapters
desired filters: --filter 53555 and --filter 00000

Best regards

**Comment by StevenWingett** [comment]
Hi Edson,

Thank you for your email.  FastQ Screen does no allow the user to specify --filter twice on the command line.  Could the example you sent me be solved with the command below?

--filter 5-555

All the best,

Steven

**Comment by edsonmachado** [comment]
Hi Steven,

About the suggestion  --filter 5-555, maybe not offer what I want. I'm not sure...
If I understood right the way that works option "-", in this case, the filter 5-555 will keep a read that multi-maps with Human and Ecoli but doesn't map with the Mouse genome. Right?
In my case, reads that don't map with Mouse should be kept only if they don't map with any genome.

Thank you for your feedback.

Best regards.

**Comment by StevenWingett** [comment]
Hi Edson,

I now believe I understand your requirements.  I think you are correct that at the moment this requires successive rounds of filtering.  It may be something to add in the future, but typically most users need a more simple 1-step filtering.  I hope that 2 stages of filtering is not too much of a problem.   

Thanks very much for your feedback!

All the best,

Steven
